### PR TITLE
Multigrid master

### PR DESCRIPTION
**Pull request by ahshahid**
Requirement is to pass properties starting with  gemfire-grid.  to be passed to GemFireStore.
If the prefix is not done, it gets flitered in a function  ( because it is not belonging otherwise to store or snappy-spark).

(Fill in the changes here)

## Patch testing

(Fill in the details about how this patch was tested)

## ReleaseNotes.txt changes

(Does this change require an entry in ReleaseNotes.txt? If yes, has it been added to it?)

## Other PRs 

(Does this change require changes in other projects- store, spark, spark-jobserver, aqp? Add the links of PR of the other subprojects that are related to this change)

### CODE REVIEW

**Comment by sumwale** [comment]
@ahshahid Why not use the standard Spark convention of "spark." prefixed properties i.e. "spark.gemfire-grid.xx" or better something like "spark.gemfire.connector.grid.xx". Connectors should not add new unique prefixes to be handled in the product.

**Comment by ahshahid** [comment]
Jags & me thought to keep it small & very specific to gemfire property.
Bringing Jags in loop. I am ok with either..

**Comment by ahshahid** [comment]
Just to clarify, that property is actually without prefix .

**Comment by sumwale** [comment]
"snappydata." prefix is one and the only special case that is allowed in SnappyData product apart from "spark." (for obvious reasons). Even for GemFireXD we changed it to "snappydata.store." and we should certainly not change that for an external connector. Please change the prefix to "spark.gemfire..." something and then this PR is not required and should be closed.

**Comment by ahshahid** [comment]
i see. in which case would the conf file need full specification like spark.gemfire.-grid.xx & would this property be available in the map in GemFireStore?

**Comment by ahshahid** [comment]
Sumedh, would a spark prefixed property be available in the GemFireStore.boot?

**Comment by ahshahid** [comment]
@sumwale  Could you please clarify this thing , will a spark prefixed property be available in GemStore.boot? If not , what prefix is needed? It would be better if it is not  preceded by store.

**Comment by sumwale** [comment]
Yes "spark." prefixed properties are available in SparkConf like what this patch is trying to do.

**Comment by ahshahid** [comment]
Sumedh , but will sparkConf it self be accessible in GemFireStore.boot ?
Pls note that this spark prefixed property is needed in gemFireStore.boot

**Comment by sumwale** [comment]
Yes all properties passed at boot time are available in GemFireStore.boot. All "spark." and "snappydata." ones are also set into the SparkConf of LeadImpl (like in the code you changed in this PR) so you can get it both via GemFireStore.boot or SparkEnv.get.

**Comment by ahshahid** [comment]
ok. thanks

**Comment by ahshahid** [comment]
and that woudl be the case on servers too?  because these props would also
be needed GemFireStore.boot of servers. Where I suppose SparkEnv does not
work ( or does it?)

**Comment by sumwale** [comment]
It is available in the properties of GemFireStore.boot if set in conf/servers. It is also available in SparkEnv.get.conf fetching from driver on lead after ExecutorInitiator is started (i.e. after the GemFireStore.startExecutor call in boot). In first case this property has to be set on all servers explicitly. The second way is the cleaner and more Spark-like way where properties will be set only on driver (leads) and executors will get it during their execute.

**Comment by ahshahid** [comment]
OK. Start executor would be late , becoz cache would be created by then. I
m testing explicitly passing on lead and server confs

**Pull request merged**
