### PR TITLE
First cut of SnappyImplicits for DataFrames

### PR DESCRIPTION
**Pull request by rishitesh**
Please review the approach I am taking for handling SnappyImplicits.

The usage code will be something like
     List<JavaBean> data = Arrays.asList(new JavaBean(1, 2, 3), new JavaBean(3, 4, 5));
    JavaRDD<JavaBean> s1 = jsc.parallelize(data);
    DataFrame dataDF = snc.createDataFrame(s1, JavaBean.class);

    Map<String, Object> options = new HashMap<String, Object>();

    options.put("qcs", "col1");
    options.put("fraction", 0.01);
    options.put("strataReservoirSize", 50);

    SampleDataFrame sampleDataFrame = snappyApis(dataDF).stratifiedSample(options);

    sampleDataFrame.registerTempTable("JavaBean");
    DataFrame countDF = snc.sql("select * from JavaBean");
    Assert.assertTrue(countDF.count() > 0);

### CODE REVIEW

**Comment by rishitesh** [comment]
This PR is to give an idea how our implicits can be accessed. I can't merge it now as I have to add all other APIs and tests.

**Comment by ymahajan** [comment]
SnappyJavaAPI would be a better name than SnappyJavaUtils, it's not really utils but APIs

**Comment by ymahajan** [comment]
RDDJavaFunctions, DataFrameJavaFunctions classes look good

**Comment by ymahajan** [comment]
RDDJavaFunctions, DataFrameJavaFunctions classes look good

**Comment by ymahajan** [comment]
Do we have unit tests for these APIs ?

**Comment by rishitesh** [comment]
Yes : Unit test is in this PR.  https://github.com/SnappyDataInc/snappy-aqp/pull/33

**Comment by ymahajan** [comment]
I agree with you that there could be a better name for 'snappyApis'

**Comment by jramnara** [comment]
I prefer SnappyJavaUtils ... instead of API suffix. Checkout cassandra, others for ideas. I don't have enough context to comment on this. 
Is the only API in consideration here is 'stratifiedSample' ? AQP team, sumedh should comment.

**Comment by rishitesh** [comment]
No, all other APIs are also included in the PR. I just gave an example of stratifiedSample.

**Comment by rishitesh** [comment]
Full code is in https://github.com/SnappyDataInc/snappy-aqp/pull/33

**Pull request merged**
