### PR TITLE
Use same conn for rowbuffer and columnstore

### PR DESCRIPTION
**Pull request by suranjan**
For update/delete on column table use the same
  conn for operation on rowbuffer as well as columnstore
  It makes commit/rollback easier to do.

## Changes proposed in this pull request

(Fill in the changes here)

## Patch testing

(Fill in the details about how this patch was tested)

## ReleaseNotes.txt changes

(Does this change require an entry in ReleaseNotes.txt? If yes, has it been added to it?)

## Other PRs 

(Does this change require changes in other projects- store, spark, spark-jobserver, aqp? Add the links of PR of the other subprojects that are related to this change)

### CODE REVIEW

**Comment by sumwale** [comment]
Why this code duplication everywhere in generated code? This is confusing and easy to get wrong (and if there is some error in one place then will need to correct all of insert/update/delete plans). Please move out these explicit commit/rollback to a separate task listener used everywhere uniformly in insert/update/delete plans.

**Comment by suranjan** [comment]
@sumwale Ok. will refactor. TaskListener can only be used for commit/rollback.

Call to begin will have to be as it is? like in initCode.

**Comment by sumwale** [comment]
Can't the begin be done in its constructor?

**Comment by sumwale** [comment]
Obsoleted by https://github.com/SnappyDataInc/snappydata/pull/781

**Pull request closed without merging**
