### PR TITLE
Added python api documentation

### PR DESCRIPTION
**Pull request by nthanvi**
## Changes proposed in this pull request

documentation python streaming api

## Patch testing
NA
(Fill in the details that how was this patch tested)

## Other PRs 
NA
(Does this change required changes in other projects- store, spark, spark-jobserver, aqp? Add the links of PR of the other subprojects that are related to this change)

### CODE REVIEW

**Comment by nthanvi** [comment]
@ymahajan  I think this document should be split in two documents. one containing the API info and another containing the job info. what you think?

**Comment by ymahajan** [comment]
'schema Dstream' should be 'SchemaDStream'
'SnappyStreaming Context' should be 'SnappyStreamingContext'

**Comment by ymahajan** [comment]
@nthanvi, we can move these to gettingStarted.md as you suggested

**Comment by ymahajan** [comment]
Instead of 
'The Snappy Python Streaming Api have limited features in compare to it's corresponding scala API. It does not support TopK structures and registerCQ.'
We can add following 
'Currently we don't have Python APIs added for continuous queries and AQP/Sampling.'

**Comment by nthanvi** [comment]
@ymahajan  - I have taken care of the review comments except that the API's are yet not added to the GettingStarted Doc As I think that before doing that it would be a better to discuss in the scrum meeting and take others opinion as well.

Merging the commit for now so that at least we  have some documentation of python API in place.

**Pull request merged**
