### PR TITLE
SNAP-1840

### PR DESCRIPTION
**Pull request by ymahajan**
Fixed SNAP-1840, TPCH Q22 query execution failure
Added a simple test to reproduce the issue

## Patch testing

precheckin 

## ReleaseNotes.txt changes

None

## Other PRs 

None

### CODE REVIEW

**Comment by hbhanawat** [comment]
The actual problem is why the code generation is being done on the executor side. This should not ever happen. This PR fixes the side effect but not the actual problem.

**Comment by ymahajan** [comment]
See this fix in upstream Spark - https://github.com/apache/spark/pull/13569
ScalarSubqueryExec reference the child plan at execution time. Also this is not related to multi node setup(driver/executor) etc, this was reproduced in a simple scalatest added in this PR.

**Comment by hbhanawat** [comment]
Tried your test, it is generating some other error and it looks like your fix fix the problem at hand. But if you see the exception on the bug, it says has the following line: basicPhysicalOperators.scala:216 which is FilterExec.doExecute.Why FilterExec.doExecute is getting called and not the code generation functions?

**Comment by sumwale** [comment]
Agree with Hemant. We need to find why the difference in plans in embedded mode vs connector mode. The code generation and execution paths should be identical for the two cases (except that latter will fetch column batches using thrift connection vs former using region API).

**Pull request closed without merging**
