### PR TITLE
Snap 999

### PR DESCRIPTION
**Pull request by nthanvi**
## Changes proposed in this pull request

Only the application Job jar will be loaded through the job server route and rest all the dependency and user jars should be loaded through the snappy  store install jar command.

should fix following bugs 
SNAP-999
SNAP-1133
SNAP-1059
## Patch testing

Manual testing , DUnit , JUnit, HydraTest ,Precheckin
## ReleaseNotes.txt changes

(Does this change require an entry in ReleaseNotes.txt? If yes, has it been added to it?)
Yes.
## Other PRs

https://github.com/SnappyDataInc/spark/pull/19
https://github.com/SnappyDataInc/spark-jobserver/pull/3

### CODE REVIEW

**Comment by dhavalstr** [comment]
Can one of the admins verify this patch?

**Comment by nthanvi** [comment]
Run precheckin

**Comment by nthanvi** [comment]
Run precheckin

**Comment by SachinJanani** [comment]
Run precheckin

**Comment by SachinJanani** [comment]
Run precheckin

**Comment by dhavalstr** [comment]
Run precheckin

**Comment by dhavalstr** [comment]
Run precheckin

**Comment by nthanvi** [comment]
Run precheckin

**Pull request merged**
