### PR TITLE
SNAP-1808 Create cachedbatch tables in user's schema instead of the earlier common schema SNAPPYSYS_INTERNAL

### PR DESCRIPTION
**Pull request by ashetkar**
## Changes proposed in this pull request
SNAP-1808 Create cachedbatch tables in user's schema instead of the earlier common schema SNAPPYSYS_INTERNAL.
Once okayed, this will be merged into SNAP-1656.

## Patch testing
precheckin running

## ReleaseNotes.txt changes
NA

## Other PRs 
https://github.com/SnappyDataInc/snappy-store/pull/239

### CODE REVIEW

**Comment by vivekwiz** [comment]
I still see usage of io.snappydata.Constant#SHADOW_SCHEMA_NAME in
1. org.apache.spark.sql.SnappySession#getIndexTable
2. org.apache.spark.sql.hive.QualifiedTableName
3. io.snappydata.core.aqp.SamplingAccuracySuite#columnBatchTableName

Please update all above code as per new protocol.

**Comment by ashetkar** [comment]
> 1. org.apache.spark.sql.SnappySession#getIndexTable

This got missed during cherry-picking the changes to SNAP-1808. Added now. Thanks.

> 2. org.apache.spark.sql.hive.QualifiedTableName

Do not see any reference here. Which method?

> 3. io.snappydata.core.aqp.SamplingAccuracySuite#columnBatchTableName

Already taken care of in https://github.com/SnappyDataInc/snappy-aqp/pull/153

**Comment by vivekwiz** [comment]
#2 was related to #1 that you have taken care now.

**Comment by ashetkar** [comment]
Closing this PR as another PR created against master #712 .

**Pull request closed without merging**
