### PR TITLE
CachedPlanHelper is now removed from the plan information for UI.

### PR DESCRIPTION
**Pull request by kneeraj**
## Changes proposed in this pull request

CachedPlanHelperExec spark plan which has been introduced to facilitate Tokenization use to also show up in the dashboard UI. This is not useful to the user and so removing it from the dispaly by calling a simple transform.

## Patch testing

Manual.

## ReleaseNotes.txt changes

No.

## Other PRs 

None.

### CODE REVIEW

**Comment by kneeraj** [comment]
@rishitesh  it won't be a problem as this is just for the UI we are transforming and a new plan tree object is returned. The executedPLan is never touched.

**Comment by sumwale** [comment]
As a general comment we may need to see how much overhead does these additional plan transformations have for low-latency queries.

**Comment by kneeraj** [comment]
>> As a general comment we may need to see how much overhead does these additional plan transformations have for low-latency queries.

True. This was going in my mind too. May be we need some discussion here as to how to minimize the effect on low latency queries or should be handled differently.

So for now should I go ahead and merge?

**Comment by sumwale** [comment]
Fine for merge, but we may need to note it down somewhere. We will be coming to low latency query performance soon.

**Comment by sumwale** [comment]
Btw, the PlanInfo caching was done because I did see overhead of PlanInfo creation for low latency queries as part of general optimizations that we done in SNAP-1191. We need to circle back on it and see how much it effects overall performance.

**Pull request merged**
