### PR TITLE
SNAP-1268: Code changes to start SnappyTableStatsProviderService service only once.

### PR DESCRIPTION
**Pull request by snappy-sachin**
## Changes proposed in this pull request

* SnappyTableStatsProviderService is started only once.

## Patch testing

* Tested Manually
* Running Precheckin

### CODE REVIEW

**Comment by snappy-sachin** [comment]
Run precheckin

**Comment by sumwale** [comment]
@snappy-sachin Is this relevant anymore with current code? If not then please close.

**Comment by sumwale** [comment]
@snappy-sachin Can you comment about the relevance of this issue else will close.

**Comment by snappy-sachin** [comment]
Yes Sumedh,
This code change is still required.
I will get it reviewed from Suranjan and will merge it into master.

**Comment by snappy-sachin** [comment]
Created new branch _SNAP-1268-10_ and PR
_https://github.com/SnappyDataInc/snappydata/pull/738_

Closing this PR as discussed.

**Pull request closed without merging**
