### PR TITLE
[SNAP-995] Modify Snappydata Zeppelin interpreter to support spark 2.0

### PR DESCRIPTION
**Pull request by SachinJanani**
## Changes proposed in this pull request
-Changes in zeppelin interpreter related Spark 2.0

## Patch testing
Ran Precheckin some test where failing which are not related to this PR

## ReleaseNotes.txt changes

Does this change require an entry in ReleaseNotes.txt? No

## Other PRs 

(Does this change require changes in other projects- store, spark, spark-jobserver, aqp? Add the links of PR of the other subprojects that are related to this change) N/A

### CODE REVIEW

**Comment by sumwale** [comment]
@SachinJanani @rishitesh As I have mentioned before, in my opinion the entire zeppelin dependencies should be moved out into external repository. We can keep very minimal interfaces in the main product to load up zeppelin if required. Lets discuss in the next huddle with Jags.

**Comment by jramnara** [comment]
I thought we already agreed that zeppelin (product) should NOT be bundled,
given its size. The interpreter itself should be (even though it can also
be pulled from the maven repo).

-----
Jags
SnappyData blog <http://www.snappydata.io/blog>
Download binary, source <https://github.com/SnappyDataInc/snappydata>

**Comment by rishitesh** [comment]
I am all in for reducing number of dependency in core product. As such it has started to grow. Number of jars are almost double of that of Spark. Lets discuss what are the complications Sachin might face.

**Comment by SachinJanani** [comment]
Closing this PR and created separate repo for zeppelin.Will raise a separate PR to remove code related to zeppelin from snappy-cluster

**Pull request closed without merging**
