### PR TITLE
SNAP-1003 snappy-store filtered from publishLocal Target

### PR DESCRIPTION
**Pull request by dhavalstr**
## Changes proposed in this pull request

Due to publishLocal target was broken
snappy-store filtered out from publishLocal
Added dependencies required by store/build.gradle in to main build.gradle.

## Patch testing

(Fill in the details about how this patch was tested)

## ReleaseNotes.txt changes

(Does this change require an entry in ReleaseNotes.txt? If yes, has it been added to it?)

## Other PRs 

(Does this change require changes in other projects- store, spark, spark-jobserver, aqp? Add the links of PR of the other subprojects that are related to this change)

### CODE REVIEW

**Comment by sumwale** [comment]
@dhavalstr Why are other changes required (I think mostly copied from store build.gradle)? Only the changes to publishLocal and publishMaven should be enough.

**Comment by dhavalstr** [comment]
@sumwale There were jgMagic task was failing and due to that I had do copy all the required parameters from store/sbuild.gradle  to  main build.gradle

**Comment by dhavalstr** [comment]
@sumwale Can we merge this to master if it is fine from your side?

**Comment by sumwale** [comment]
@dhavalstr Can you try again without the other changes and just the publishLocal change because that has been working for me just fine?

**Comment by sumwale** [comment]
@dhavalstr If current code is working fine as you mentioned, then please close this.

**Pull request closed without merging**
