### PR TITLE
[SNAP-2347] Fix for row tables getting dropped.

### PR DESCRIPTION
**Pull request by rishitesh**
## Changes proposed in this pull request
There was a small window when the connection is lost to the JDBC source JDBCMutable relation might drop the table, thinking of a failed initialization. 

## Patch testing

pre-checkin

## ReleaseNotes.txt changes

NA

## Other PRs 
Na

### CODE REVIEW

**Comment by kneeraj** [comment]
@rishitesh essentially we are keeping a member variable as a flag. Is there a chance that when a cached relation is returned we may have problems? Is it possible to do the same thing passing around local variables.

**Comment by rishitesh** [comment]
@kneeraj A cached relation will not call createRelation , hence the destroy in case of a failure will not get called.

**Comment by kneeraj** [comment]
Ok. Not insisting but I think I would clear the field to false once 'createRelation' has succeeded anyways.
Rest looks fine to me.

**Comment by rishitesh** [comment]
@kneeraj Ok I can add that.

**Comment by rishitesh** [comment]
@kneeraj This variable is used only when a new relation is getting created, so we are safe here.

**Pull request merged**
