### PR TITLE
[SNAP-1199] Fix for SNAP-1199.Treat external table as external instea…

### PR DESCRIPTION
**Pull request by SachinJanani**
## Changes proposed in this pull request
* Treat external table as external instead of Row table to avoid catalog inconsistency while catalog cleanup

## Patch testing
Tested manually 

## ReleaseNotes.txt changes

(Does this change require an entry in ReleaseNotes.txt? If yes, has it been added to it?) No

## Other PRs 
[Store PR-130](https://github.com/SnappyDataInc/snappy-store/pull/130)

…d of Row table

### CODE REVIEW

**Comment by sumwale** [comment]
Looks good. I think you may need additions to SnappyHiveCatalog to handle this.

**Comment by jramnara** [comment]
What is this fix for? "Treat external table as external instead of Row table " ?  Do we now have meta data in our catalog to view external tables also?

**Comment by sumwale** [comment]
@jramnara We always had the meta-data and this helps in distinguishing them properly (i.e. CREATE EXTERNAL TABLE also get recreated on restart). This issue is related to visibility of these tables between split-cluster vs embedded but the same meta-data can also be used to show these on snappy-shell.

**Comment by soubhik-c** [comment]
looks good. as we discussed lets mention about Sample table cleanup handling.

**Comment by SachinJanani** [comment]
After discussing with shirish we have also handled cleanup for Sample table.This handling is done in SnappyHiveCatalog.getisTableInStoreDD

**Comment by SachinJanani** [comment]
Showing external table in snappy-shell will be handled as a part of SNAP-1208

**Pull request merged**
