### PR TITLE
[SNAP-837] Add packageTests to dtests archives to enable publishing of tests jar

### PR DESCRIPTION
**Pull request by sumwale**
## Changes proposed in this pull request

Addition of packageTests task to dtests archives enables the "-tests" jar to be published in local and remote maven.

- moved the dangling copy task in dtests/build.gradle inside testsClass.doLast
- also moved the download plugin separately into core so as to not conflict with
  store/native declaration (which runs both as sub-project or independent project)

## Patch testing

Checked publishLocal that it does place the gemfirexd-scala-tests...-tests jar in local m2 repository.

## Other PRs 

NA

### CODE REVIEW

**Comment by sumwale** [comment]
@KishorBachhav @hbhanawat I moved the dangling copy task in dtests/build.gradle in the doLast section. But it still bothers me that the task:

a) Copies to store/tests/sql which is not a dependent sub-project. It should really be copying to its own area and script should pick up from there into classpath or resource search path (or create a mega-shadow jar that includes gemfirexd-tests but that will not be preferable).

b) Uses custom hackish way to construct the full build path to copy instead of using regular project(...).buildDir.

Do you guys know the reasons for the above?

**Comment by sumwale** [comment]
@KishorBachhav @hbhanawat To clarify point a) further: the resources are all copied to the store tests, but the tests jar remains separate. This indicates buggy scripts/mechanism and also implies that hydra framework is really not extendible at all in that all confs/bts have to go into base framework directory. If that be the case, then hydra search for confs/bts should be fixed to use regular resources mechanism or something.

**Comment by KishorBachhav** [comment]
@swatisawant can speak more on this. I think she has added this copy task.

**Comment by sumwale** [comment]
I have replaced the hard-coded paths in the copy task with appropriate gradle properties.

Will go ahead with the merge if there are no comments. Will wait for comments from @swatisawant on why the config has to be copied to store/tests/sql

**Comment by swatisawant** [comment]
@sumwale - Yes, I am suppose to add the support in hydra to include DTESTS path for searching required conf and inc files similar to JTESTS and EXTRA_JTESTS.
This is the temporary solution I had used to proceed further fast and will be working on this once I have free cycle for doing the same.

**Pull request merged**
