### PR TITLE
Snap 2601: Display Tables Schema on Snappy UI

### PR DESCRIPTION
**Pull request by snappy-sachin**
## Changes proposed in this pull request

Feature Request: 
  1. Display tables schema in Tables tabular view. 
  2. Provide user control on click of which table schema is shown or hide.

Code Changes for:
  - Obtaining tables and external tables schema details.
  - Maintain tables schema details in the map to avoid obtaining same schema info repeatedly.
  - HTML changes for adding schema container to display schema details on UI.
 
Screen-shot of Actual UI is available [here](https://jira.snappydata.io/secure/attachment/12402/Table-Schema-ExpandedAndCollapsed-View.png). You can see tables expanded and collapse schema view in it.

## Patch testing

 - Tested Manually

## ReleaseNotes.txt changes

 - Yes.

## Other PRs 

  Store: https://github.com/SnappyDataInc/snappy-store/pull/430
  Spark: https://github.com/SnappyDataInc/spark/pull/125

### CODE REVIEW

**Comment by sumwale** [comment]
@snappy-sachin Please attach a couple of screenshots of how the schema looks like collapsed and expanded.

**Comment by snappy-sachin** [comment]
> @snappy-sachin Please attach a couple of screenshots of how the schema looks like collapsed and expanded.

Screen-shot of Actual UI is available [here](https://jira.snappydata.io/secure/attachment/12402/Table-Schema-ExpandedAndCollapsed-View.png). You can see tables expanded and collapse schema view in it.

**Comment by jramnara** [comment]
@snappy-sachin It is good to view the schema but viewing the schema inside the table summary view is confusing. This should be separated out and the user should be able to view the hierarchy - schema names and objects within. In fact, we could move the schema to a new tab altogether. 
We should discuss.

**Comment by snappy-sachin** [comment]
As per discussion in huddle (16th Nov 2018), Idea of displaying table schema details needs re-thinking or more specifically displaying all details specific to Table on completely new page/tab can needs to be considered. This needs more discussion.
For now closing this and relevant PRs( Store: SnappyDataInc/snappy-store#430, Spark: SnappyDataInc/spark#125 ).

**Pull request closed without merging**
